twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        admin_dir: 'admin'
        admin_layout_dir: 'admin/layout'
        admin_layout_partial_dir: 'admin/layout/partial'
        admin_component_dir: 'admin/component'
        admin_component_table_dir: 'admin/component/table'

        asset_admin_dir: 'assets/admin'
        asset_admin_css_dir: 'assets/admin/css'
        asset_admin_js_dir: 'assets/admin/js'
        asset_admin_image_dir: 'assets/admin/images'

        asset_admin_v2_dir: 'assets/admin/v2'
        asset_admin_v2_css_dir: 'assets/admin/v2/css'
        asset_admin_v2_js_dir: 'assets/admin/v2/js'
        asset_admin_v2_image_dir: 'assets/admin/v2/img'
        asset_admin_v2_fonts_dir: 'assets/admin/v2/fonts'
