twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        domain_url: '%env(DOMAIN_URL)%'
        js_folder: '%env(JS_FOLDER)%'
        google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
        include_matomo: '%env(INCLUDE_MATOMO)%'
        matomo_analytics: '%env(MATOMO_ANALYTICS)%'
        
        ### general path WEB in template: =========================
        web_component_dir: 'web/component'
        web_layout_dir: 'web/layout'
        web_layout_global_dir: 'web/layout/global'
        web_layout_partial_dir: 'web/layout/partial'

        # page:
        web_page_dir: 'web/page/'
        web_home_dir: 'web/page/home/'
        web_dean_dir: 'web/page/dean/'

        #public asset:
        asset_web_dir: 'assets/web'
        asset_web_css_dir: 'assets/web/css'
        asset_web_js_dir: 'assets/web/js'
        asset_web_image_dir: 'assets/web/images'
        
        #### Admin ================================================
        admin_dir: 'admin'
        admin_layout_dir: 'admin/layout'
        admin_layout_partial_dir: 'admin/layout/partial'
        admin_component_dir: 'admin/component'
        admin_component_table_dir: 'admin/component/table'

        #page:
        admin_country_dir: 'admin/page/country'
        admin_area_dir: 'admin/page/area'
        admin_vote_manager_dir: 'admin/page/vote_manager'

        #public asset:
        asset_admin_dir: 'assets/admin'
        asset_admin_css_dir: 'assets/admin/css'
        asset_admin_js_dir: 'assets/admin/js'
        asset_admin_image_dir: 'assets/admin/images'

        asset_admin_v2_dir: 'assets/admin/v2'
        asset_admin_v2_css_dir: 'assets/admin/v2/css'
        asset_admin_v2_js_dir: 'assets/admin/v2/js'
        asset_admin_v2_image_dir: 'assets/admin/v2/img'
        asset_admin_v2_fonts_dir: 'assets/admin/v2/fonts'
